sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

script:
  - set -e
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - npm test
  - npm run eslint
  - docker build -t blutner/ocomis-authentication-api:latest .
  - docker tag "blutner/ocomis-authentication-api:latest" "blutner/ocomis-authentication-api:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-authentication-api:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-authentication-api:latest"
  - docker logout
